### ISSUE TITLE
cicero command line model error when running in a windows powershell

### ISSUE THREAD

**Issue by DeweyWald** [accordproject/cicero-vscode-extension#11]
When I run cicero parse or archive I get a model error every time. I upload the same code to Template Studio and if validates and I can create a CTA from template studio.

The error:
cicero archive --template rideshare-driver-requirements-service --archiveFile rideshare-driver-requirements-service
11:05:53 AM - error: Failed to find an asset that extends org.accordproject.cicero.contract.AccordClause in rideshare-driver-requirements-service. The model for the template must contain a single asset that extends org.accordproject.cicero.contract.AccordClause.

The model file:
namespace docusign.rideshare.requirements

import org.accordproject.cicero.contract.* from https://models.accordproject.org/cicero/contract.cto
import org.accordproject.cicero.runtime.* from https://models.accordproject.org/cicero/runtime.cto

transaction RideshareRequirementsServiceRequest extends Request {
  o Boolean checkDriver
  o String idNumber
  o String insuranceCarrier
  o String insuranceNumber
  o Boolean overEighteen
  o Boolean oneYearExperience
  o Boolean validLicense
  o Boolean twoAccidentsOrLess
  o Boolean twoMovingViolationsOrLess
  o Boolean zeroDistractedViolation
  o Boolean zeroMajorViolations
  o Boolean oneAccidentOneViolation
  o Boolean validInsurance
}

transaction RideshareRequirementsServiceResponse extends Response {
  o String validInsurance
  o String validIdForRideShare
  o String validLicense
  o String oneAccidentOneViolationThreeYearsOrLess
  o String twoAccidentsThreeYearsOrLess
  o String twoViolationsThreeYearsOrLess
  o String zeroDistractedViolationsThreeYears
  o String zeroMajorViolationsFiveYears
  o String validRequirements
  o String valideRecord
}

asset RideshareRequirementsServiceClause extends AccordClause {
}

**Comment by jeromesimeon** [comment]
Is this an issue on the VSCode extension? Or should this be filed on the main Cicero repository here: https://github.com/accordproject/cicero

**Comment by DeweyWald** [comment]
oh, probably the main cicero rep

**Comment by DeweyWald** [comment]
I will move it

**Comment by jeromesimeon** [comment]
Just with a quick read through the issue, I have the impression that this model file should work (and not raise the error mentioned). If this is a Windows-only issue, it would help to have information about the environment (which Windows version, Node version) and a sample archive to test.

**Comment by DeweyWald** [comment]
Ok I will add that as well

**Comment by jeromesimeon** [comment]
thanks!

**Comment by DeweyWald** [comment]
moved to https://github.com/accordproject/cicero/issues/408
