### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by parammittal16** [accordproject/cicero-vscode-extension#15]
There are some grammatical issues in Readme file.
I want to correct them and work on this issue as of Hackoberfest.

**Comment by parammittal16** [comment]
@dselman @irmerk plz can Hackoberfest label be added here

**Comment by yesji** [comment]
@parammittal16 are you working on this? if not can I take this up?

**Comment by irmerk** [comment]
@yesji if @parammittal16 hasn't opened a PR by tomorrow (Monday), go for it.

**Comment by parammittal16** [comment]
@irmerk but I have already open a PR and it is also merged successfully. Which makes this issue solved.

**Comment by irmerk** [comment]
@parammittal16 great. This is an example of how it's useful to provide the issue link reference in the PR so we can see it here.
