### ISSUE TITLE
Spurious error reported when sample.txt is opened after model.cto

### ISSUE THREAD

**Issue by adrianffletcher** [accordproject/cicero-vscode-extension#2]
When the helloworld sample is opened and the model.cto file is opened in the editor followed by the sample.txt file then a spurious error is reported.

If the template.tem file is subsequently opened and the sample.txt file is re-opened then the problem resolves. This can be repeated to your heart's content.

<img width="1433" alt="Screen Shot 2019-06-28 at 12 47 51" src="https://user-images.githubusercontent.com/29235349/60340436-739e8b80-99a3-11e9-8142-5ce9c288e627.png">

[Kapture 2019-06-28 at 12.43.13.mp4.zip](https://github.com/accordproject/cicero-vscode-extension/files/3339041/Kapture.2019-06-28.at.12.43.13.mp4.zip)

**Comment by dselman** [comment]
Fixed
