### ISSUE TITLE
Adding Snippets for Concerto language

### ISSUE THREAD

**Issue by iRohitSingh** [accordproject/cicero-vscode-extension#38]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Snippets for model.cto file.

**Comment by iRohitSingh** [comment]
I am working on this.

**Comment by jeromesimeon** [comment]
Could you explain what this is? I'm not familiar with "snippets".

**Comment by iRohitSingh** [comment]
@jeromesimeon
```
 "Code Snippet" is a term used to describe a small portion of re-usable source code, machine code, or text. They allow a programmer to avoid typing repetitive code during the course of routine programming.
```
Some example like you want to create classes in .cto file then you have to write
```
asset Vehicle identified by vin {
  o String vin
}
```
what code snippets do is, you don't have to write the asset again and again. You just type assets and press tab a sample format of assets is provided to you. You can navigate through the tab and just write the name for that asset. You can find code snippets for any framework like react js, Angular, Bootstrap and many more.

I will attach a gif that explains what is code snippets for concerto language.

**Comment by iRohitSingh** [comment]
@jeromesimeon Here is the Gif :)

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/61353484/75116087-b461b800-568a-11ea-8952-a02b20f567a8.gif)

**Comment by yashwanthambati** [comment]
provide me a standard .cto file so that I can do according the file? 
So that I can do imports,exports and stuff related to concerto files.

**Comment by irmerk** [comment]
Tagging @dselman and @mttrbrts on this.

**Comment by jeromesimeon** [comment]
I quite like this idea. I would like a bit more details on what the requirements are:

- what should the field names based on?
- can types be filled in on other class names present in the model?
- how does it relate / overlaps with #36 

Also I think I would like some UX review and get a sense of how it would affect the user experience, help or get in the way, etc.

Maybe it's worth putting draft code around this on a branch?

**Comment by jeromesimeon** [comment]
> provide me a standard .cto file so that I can do according the file?
> So that I can do imports,exports and stuff related to concerto files.

Not sure what a standard would be, but there are many examples in : https://models.accordproject.org

Or do you mean something else?

**Comment by yashwanthambati** [comment]
yeah. I can prepare according to the models. Thanks

**Comment by yashwanthambati** [comment]
@jeromesimeon  Yeah I can do according to models. Thanks

**Comment by iFlameing** [comment]
> I quite like this idea. I would like a bit more details on what the requirements are:
> 
> * what should the field names based on?
> * can types be filled in on other class names present in the model?
> * how does it relate / overlaps with #36
> 
> Also I think I would like some UX review and get a sense of how it would affect the user experience, help or get in the way, etc.
> 
> Maybe it's worth putting draft code around this on a branch?

I implemented field names based on the concerto class we can keep continuing this. Because we can only provide snippets if we already know about the class structure.

I didn't understand the second question regarding types. If You elaborate I can come up with some solution.

It is totally new feature. It doesn't relate to #36. For the implementation of IntelliSense, We have to do some discussion :)

**Comment by iRohitSingh** [comment]
> I quite like this idea. I would like a bit more details on what the requirements are:
> 
>     * what should the field names based on?
> 
>     * can types be filled in on other class names present in the model?
> 
>     * how does it relate / overlaps with #36
> 
> 
> Also I think I would like some UX review and get a sense of how it would affect the user experience, help or get in the way, etc.
> 
> Maybe it's worth putting draft code around this on a branch?

I have implemented the field names using the concerto class and continuing this will be a good idea because we can provide snippets only if we know the class structure provided by concerto language.

I am unable to understand the 2nd question related to types.

It is totally new feature It has nothing related to #36. For adding IntelliSense we need to discuss.

**Comment by iRohitSingh** [comment]
@jeromesimeon Regarding user experience almost every language plugin provides snippets. It can be seen as when you are writing lots of the class name in model .cto file then you don't have to type transaction, concept, assets, abstract asset every time.

I have already created a pr for this [#39](https://github.com/accordproject/cicero-vscode-extension/pull/39). If you have any more question please! tell me :)

**Comment by iRohitSingh** [comment]
@jeromesimeon Do You need any more information. Do you have any question regarding this I will be happy to discuss with you :)

**Comment by dselman** [comment]
Nice work - I think this would be a useful addition to Concerto, and for Ergo as well.

**Comment by iRohitSingh** [comment]
@dselman can you give me some pointer regarding #36 I researched a bit about adding IntelliSense to vscode for concerto language. I saw a different project like adding IntelliSense like c++, javascript and typescript. But they provide IntelliSense using LSP(I think). I am learning what LSP is and how it works. Can you explain something about it? please!!!!
