### ISSUE TITLE
Version numbers confusing

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero-vscode-extension#4]
Any reason the version numbers shouldn't be aligned with the Cicero one? (at least the major/minor number?).

e.g., Cicero VSCode extension 0.13.* would be for Cicero 0.13.*

**Comment by dselman** [comment]
I think aligning the version numbers makes sense.

**Comment by dselman** [comment]
The major/minor version number is now aligned with the Cicero version.
