### ISSUE TITLE
Improving the code snippets for concerto language

### ISSUE THREAD

**Issue by algokun** [accordproject/cicero-vscode-extension#44]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
More additional Snippets for model.cto file

**Comment by algokun** [comment]
I would like to improve the existing code snippets for the concerto snippets for the extension

**Comment by algokun** [comment]
when it comes to code snippets, every language plugin provides snippets and also some basic documentation. I would like to improve the existing code snippets by adding more components and improve documentation

**Comment by irmerk** [comment]
Alright sounds good!

**Comment by algokun** [comment]
@irmerk could you please review this pr

**Comment by dselman** [comment]
Any progress?

**Comment by algokun** [comment]
I've completed this issue and i'm sorry that i've forgot to close.

**Comment by irmerk** [comment]
@algokun what PR was this resolved with?
