### ISSUE TITLE
Add Create Template Feature

### ISSUE THREAD

**Issue by algokun** [accordproject/cicero-vscode-extension#46]
**Is your feature request related to a problem? 
No

**Describe the solution you'd like**
I would like to suggest to add create template feature from the command pallette of vscode. This should create `helloworld` template in the selected folder and with selected project name. This will help end user to deal with the contracts on the go.

**Additional context**

**Comment by irmerk** [comment]
Not sure I understand this feature, could you explain further?

**Comment by algokun** [comment]
![Screenshot_20200307_010752](https://user-images.githubusercontent.com/21126965/76116818-a4de5980-6010-11ea-84cc-f1f4c7f3319f.png)

In vscode, there's a command palette, where we can find various command over there. My Suggestion is to include `Accord Project: Create Template` feature that will asks user to select the whole template name and the folder where he wants to create the template and then we download the `helloworld` template from the accord project template showcase and then the user can start to write the smart contract with ease(with already generated accord project template).

**Comment by irmerk** [comment]
Tagging @dselman @jeromesimeon @mttrbrts for feedback.

**Comment by dselman** [comment]
Yes, I like the idea. Note that there is already a Yeoman template for a Hello World template - so you may be able to automate running that.

**Comment by dselman** [comment]
This video shows how to install the Yeoman extension for VSCode and use it to create a new template:
https://vimeo.com/444483242

I'm going to close this for now.
