### ISSUE TITLE
Cannot run `Attach to server` debug option

### ISSUE THREAD

**Issue by adrijshikhar** [accordproject/cicero-vscode-extension#52]
**Describe the bug**
Whenever I try to run `Attach to server` debug option, it gives me this error
![Screenshot_20200318_174238](https://user-images.githubusercontent.com/41939219/76980114-cc151f00-695e-11ea-806b-397df879b78f.png)
I was following this guide to setup server and client of extension in debug mode in vscode.
https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#debugging-both-client-and-server

**To Reproduce**
1. Go to 'Run'
2. Click on dropdown at the top and select `Attach to server` option
3. See error

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04.3
 - VSCode Insiders 1.44

**Comment by adrijshikhar** [comment]
`Client + Server` runs flawlessly

**Comment by dselman** [comment]
Need more information.
