### ISSUE TITLE
Support for stand-alone Ergo or Concerto files

### ISSUE THREAD

**Issue by Rikki407** [accordproject/cicero-vscode-extension#53]
Running the extension on stand-alone Ergo or Concerto files introduces an infinite loop in search for the package.json file, due to which no error message is logged and the server essentially crashes
This can be traced back to the while-loop in the getTemplateRoot function in server.ts file

`function getTemplateRoot(pathStr, textDocument, diagnosticMap) {

    let currentPath = pathStr;
    connection.console.log(`Rikkic ${currentPath}`);

    while(currentPath !== '.') {
        connection.console.log( `- ${currentPath}`);

        try {
            const packageJsonContents = getEditedFileContents(currentPath + '/package.json');
            const packageJson = JSON.parse(packageJsonContents);
            if(packageJson.accordproject) {
                return currentPath;
            }
        }
        catch(err) {
            connection.console.log( `- exception ${err}`);
            currentPath = path.normalize(path.join(currentPath, '..'));
        }
    }

    connection.console.log( `Failed to find template path for ${pathStr}`);
    const error = {message: `${pathStr} is not a sub-folder of an Accord Project template. Ensure a parent folder contains a valid package.json.`};
    pushDiagnostic(DiagnosticSeverity.Error, textDocument, error, 'template', diagnosticMap);
    return null;
}
`

**Comment by dselman** [comment]
Thank you @Rikki407 I merged this in: https://github.com/accordproject/cicero-vscode-extension/commit/9b36f6d98501bbf0351775233fbae938b3bc4bbb
