### ISSUE TITLE
VSCode CPU consumption rising at 100% after the installation of the extension

### ISSUE THREAD

**Issue by nicoSix** [accordproject/cicero-vscode-extension#57]
**Describe the bug**
When installed, CPU consumption of VSCode rises from <10% to 100%.

**To Reproduce:**

1. Go to VS Code
2. Install the extension while monitoring CPU comp.

**Expected behavior**
Normal CPU consumption

**Desktop (please complete the following information):**
cicero-vscode-extension 0.20.9 (current)
VS Code 1.43.0
Ubuntu 18.04.4 LTS 

If it may help, here are my VSCode extensions list : 
accordproject.cicero-vscode-extension
James-Yu.latex-workshop
JuanBlanco.solidity
ms-python.python
tomoki1207.pdf
wwm.better-align

**Comment by iRohitSingh** [comment]
@nicoSix @jeromesimeon  I did a test for uninstalling and reinstalling the extension but didn't find the increase in the CPU consumption. I have also attached the gif. If I am wrong, please!!! how I can reproduce it.

**Comment by nicoSix** [comment]
@iRohitSingh I tried again but doing something different: last time, I installed the extension with accordproject/ergo folder open in Code. I tried instead with only one example opened (eg. acceptance-of-delivery contract), my CPU consumption still rises. 

Let me know if I can help by providing information! I will try to install the extension on Windows but I'm expecting it to work.

**Comment by dselman** [comment]
Stale.
